/* instruction texts that appear at different levels of zoom */
var defaultSpinInstruction = "Rotar en el sentido de las manecillas del reloj para acercar la imagen";
var defaultTiltInstruction = "Inclinar hacia abajo y arriba para movere hacia el Norte";
var huntForHotSpotTiltInstruction = "tilt to hunt for hotspot";
var huntForHotSpotSpinInstruction = "spin clockwise to view hotspot";
var spinInToSeeCards= "spin clockwise to learn about this site";
var spinOutToSeeCards = "spin counterclockwise to learn about this site ";
var zoomInToActiveRegions = "zoom in on the active regions";
var spinToSeeMoreCards = "spin to see more cards about this site";

var siteCardStartLayer = 7;

var zoomLayers = {
  '0' : { 
    'pannable' : true,
    'mapZoom' : 3,
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
  '1' : { 
    'mapZoom' : 4,
    'pannable' : true,
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
  '2' : { 
    'pannable' : true,
    'mapZoom' : 5,
    "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
  '3' : { 
    'pannable' : true,
    'mapZoom' : 6,
        "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
  '4': {
    'showLabels': true,
    'pannable' : true,
    'mapZoom' : 7,
        "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
  '5': {
    'showLabels': true,
    'pannable' : true,
    'mapZoom' : 8,
        "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
  '6': {
    'showLabels': true,
    'pannable' : true,
    'mapZoom' : 9,
        "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },

  '7': { 
    'showLabels': true,
    'pannable' : true,
    'mapZoom' : 10,
        "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
  '8': {
    'showLabels': true,
    'pannable' : true,
    'mapZoom' : 11,
        "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },

  '9': {
    'showLabels': true,
    'pannable' : true,
    'mapZoom' : 12,
    "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
  '10': {
    'showLabels': true,
    'pannable' : true,
    'mapZoom' : 13,
        "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
  '11': {
    'showLabels': true,
    'pannable' : true,
    'mapZoom' : 14,
    'imageSequenceLayer': 1,
    "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",

    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
  '12': {
    'showLabels': true,
    'pannable' : true,
     'mapZoom' : 14,
    'imageSequenceLayer': 2,
      "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",


    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
 },
  '13': {
    'showLabels': true,
     'mapZoom' : 14,
    'imageSequenceLayer': 3,
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",


    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
 },
  '14': {
    'pannable' : true,
     'mapZoom' : 15,
	"Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
 },
  '15': {
    'pannable' : true,
    'mapZoom' : 16,
    "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
 '16': {
    'pannable' : true,
     'mapZoom' : 17,
     "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
 },
  '17': {
    'pannable' : true,
    'mapZoom' : 18,
    "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
  },
  '18': {
    'pannable' : true,
    'mapZoom' : 19,
    "Indio Maíz" : "site1",
    "Papahanaumokuakea" : "site2",
    "Islas Galapagos" : "site3",
    "Wirikuta" : "site4",
    "Gogorrón" : "site5",
    "El potosí" : "site6",
    "Cabo Pulmo" : "site7",
    "Cuatrociénegas" : "site8",
    "Iztaccíhuatl Popocatépetl" : "site9",
    "Calakmul" : "site10",
    "Abra Tanchipa" : "site11",
    "Banco Chinchorro" : "site12",
    "Chamela Cuixmala" : "site13",
    "Mapimí" : "site14",
    "Mariposa Monarca" : "site15",
    "Montes Azules" : "site16",
    "Pantanos Centla" : "site17",
    "Pinacate" : "site18",
    "Revillagigedo" : "site19",
    "Ría Celestún" : "site20",
    "Sierra Gorda" : "site21",
    "Tehuacán Cuicatlán" : "site22",
    "El Vizcaíno" : "site23",
    "Distrito Federal" : "site24",
    "Guadalajara" : "site25",
    "Monterrey" : "site26",
    "San Luis Potosí" : "site27",
    'spinInstruction' : defaultSpinInstruction,
    'tiltInstruction' : defaultTiltInstruction,
 },
  
  
};

var hotspots = {
  "site1" : [11.061502,-84.060465],
  "site2" : [25.510577,-170.26446],
  "site3" : [0.484251,-90.585963],
  "site4" : [23.222356,-100.9],
  "site5" : [21.440732,-100.570744],
  "site6" : [21.581002,-99.565661],
  "site7" : [23.202372,-109.295032],
  "site8" : [26.591211,-102.034935],
  "site9" : [19.06121,-98.375681],
  "site10" : [18.065249,-89.483074],
  "site11" : [22.259419465527035,-98.92966655307195],
  "site12" : [18.586687465319507,-87.33707852533801],
  "site13" : [19.3916764138632,-105.03085391474745],
  "site14" : [26.691389,-103.745556],
  "site15" : [19.459167755065373,-100.20673530372122],
  "site16" : [16.47075010567696,-91.13869762177433],
  "site17" : [18.295522068053014,-92.45385857215878],
  "site18" : [31.90508166802501,-113.76151779983411],
  "site19" : [18.83,-111.0],
  "site20" : [20.73509950968113,-90.39005350272365],
  "site21" : [21.28721664068051,-99.47750869084503],
  "site22" : [17.855865351804,-97.13771503407628],
  "site23" : [27.769414086210112,-114.15042147668764],
  "site24" : [19.427050,-99.127571],
  "site25" : [20.659649,-103.349625],
  "site26" : [25.685255,-100.305238],
  "site27" : [22.156470,-100.985541],

};

var targetWidth = 0.03; // portion of visible map

var maxZoom = 25;
var minZoom = 3;

var panScaler = 0.02;
var clicksPerRev =  256; // weirdly not 3.14159 * 4 *
var revsPerFullZoom = (maxZoom - minZoom)/8;
var clicksPerZoomLevel =  clicksPerRev / revsPerFullZoom;
var maxClicks = clicksPerRev * revsPerFullZoom * 1.0;

var defaultMarkerLabel = {
        color : '#a1e2a1',
        fontFamily : 'arial',
        fontSize: '20px',
        fontWeight: 'bold',
        text: "",
        textAlign: 'left',
      };  

var defaultIconImage = {
	// This marker is 20 pixels wide by 32 pixels high.
          size: new google.maps.Size(32, 32),
          // The origin for this image is (0, 0).
          origin: new google.maps.Point(0, 0),
          // The anchor for this image is the base of the flagpole at (0, 32).
          anchor: new google.maps.Point(16, 16),
          labelOrigin: new google.maps.Point(16, 34),

        };

var mexicoCenter = new google.maps.LatLng(23.43348438907877, -103.05326881250002);
//var laberinto = new google.maps.LatLng(22.118239, -100.998443);
var laberinto = new google.maps.LatLng(21.440732,-100.570744);
var myLatLng = laberinto;
var logoimage = {
  url: "laberinto_logo.png",
  origin: new google.maps.Point(0, 0),
      // The anchor for this image is the base of the flagpole at (0, 32).
  anchor: new google.maps.Point(0, 16)
}
